import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {modules,subtopics,courseStats} from '../data/course.mjs';
import {apiReading,apiListening,apiBrief,apiModels} from '../data/t03-api-texts.mjs';
import {apiPatterns,apiReference,apiSources} from '../data/api-contract-language.mjs';
import {t03Vocabulary} from '../data/lexicon-t03.mjs';
import {freshState,unitState,validateState,checkAnswer,isOpen,submitUnitTest,startUnitTest,scoreUnitTest,topicWorkProgress,reviewCard} from '../web/engine.mjs';
const topic=modules.find(m=>m.id==='T03'),u=topic.subtopics[1],first=topic.subtopics[0];
const all=[...u.banks.flatMap(b=>b.tasks),...u.tests.flatMap(e=>e.tasks)];
const task=s=>all.find(t=>t.id===u.id+'-'+s),words=s=>s.trim().split(/\s+/).length;
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const roundTrip=s=>validateState(JSON.parse(JSON.stringify(s)));
function complete(s,unit){const p=unitState(s,unit.id);for(const t of unit.banks.flatMap(b=>b.tasks))p.answers[t.id]=t.answer;p.examDraft.answers=Object.fromEntries(unit.tests[0].tasks.map(t=>[t.id,t.answer]));submitUnitTest(s,unit.id,'2026-09-29T22:00:00Z');return p;}
function earlier(){const s=freshState();s.moduleProgress.T03={selfChecked:true,date:'2026-09-22'};s.drafts.T03='Synthetic archive note\nNot learner work';s.cards['T03-v2']=reviewCard(null,'good',Date.UTC(2026,8,27));s.cards['T03-x-40']=reviewCard(null,'hard',Date.UTC(2026,8,28));const p=complete(s,first);p.attempts[0].reviews['T03-review-test-a-12']={score:3,reviewer:'Synthetic reviewer',date:'2026-09-29T22:01:00Z',evidence:'Synthetic fixture, not a real learner review.'};startUnitTest(s,first.id);p.examDraft.answers['T03-review-test-b-12']='Synthetic unfinished review\nSecond paragraph';s.navigation={current:'unit/T03-review/test',sections:{course:'unit/T03-review/test'},pages:{'unit/T03-review/test':{scroll:930,focus:'answer-T03-review-test-b-12',fields:{},details:[true]},'module/T03':{scroll:120,focus:'drill1',fields:{drill0:'returns',drill1:'writing\nOld answer',drill2:'edge'},details:[true]}}};s.bookmark={route:'unit/T03-review/test',scroll:930,focus:'answer-T03-review-test-b-12'};return s;}

test('T03 API has substantial distinct sections and retains its published content as testing completes T03',()=>{
 assert.equal(u.id,'T03-api');assert.deepEqual(u.prerequisites,['T03-review']);assert.equal(u.explanation.length,15);assert.equal(u.explanation.reduce((n,e)=>n+e.text.length,0),11684);assert.equal(u.examples.length,36);assert.equal(u.goals.length,8);assert.deepEqual(u.banks.map(b=>b.tasks.length),[14,14,14,14,14,12,14,12,12]);assert.equal(topic.contentStatus,'expanded');assert.equal(topic.remainingScope.length,0);assert.deepEqual([courseStats.subtopics,courseStats.practice,courseStats.testTasks],[120,10751,5252]);
});
test('T03 preserves every published review practice/test and the first forty cards',()=>{
 assert.equal(hash(first.banks),'e345375e62a69a924ed6b9303078e4340727939f1c35f126548f8ce8ac3bff56');assert.equal(hash(first.tests),'0547d49b972e021ff86216730b35052cc3169cd45799d69c6bd5a2ad01b0fd15');assert.equal(hash(t03Vocabulary.slice(0,40)),'cd5c56b62465790f9bbae5737efee0d1c6a3e29d42d1698477d7a8d8bf93c38d');assert.equal(t03Vocabulary.length,108);assert.equal(t03Vocabulary[40].id,'T03-x-41');assert.equal(t03Vocabulary.at(-1).id,'T03-x-108');assert.equal(topic.vocabulary.length,115);assert.equal(new Set(topic.vocabulary.map(c=>c.word)).size,115);for(const c of t03Vocabulary.slice(40))assert(c.context&&c.note&&c.accent==='UK'&&/^\/.+\/$/.test(c.ipa));assert(t03Vocabulary.some(c=>c.word==='rule out'&&c.kind==='фразовый глагол'));
});
test('API grammar has independent right/wrong keys rather than circular sample checks',()=>{
 for(const [suffix,right,wrong]of [['forms-1','accepts','accept'],['forms-2','accept','accepts'],['forms-3','to','of'],['forms-4','of','for'],['forms-5','be','is'],['forms-6','is','will be'],['forms-7','fails','does fail'],['forms-8','whether','if'],['test-a-1','returns','return'],['test-a-2','be','is'],['test-a-3','fails','does fail'],['test-a-4','to','of'],['test-b-1','accept','accepts'],['test-b-2','of','to'],['test-b-3','whether','if'],['test-b-4','is','will be']]){assert(!isOpen(task(suffix)));assert(checkAnswer(right,task(suffix).answer),suffix);assert(!checkAnswer(wrong,task(suffix).answer),suffix);}
 assert(task('forms-7').prompt.includes('без усиления'));assert(isOpen(task('forms-14')));assert(isOpen(task('test-a-18')));assert(isOpen(task('test-b-18')));
});
test('API input presence, null, types, permissions and message/body meanings remain distinct',()=>{
 for(const s of ['inputs-2','inputs-3','inputs-4','outcomes-1','outcomes-3','test-a-5','test-a-6','test-b-5','test-b-6'])assert(checkAnswer('no',task(s).answer),s);
 assert(checkAnswer('general',task('inputs-1').answer));assert(checkAnswer('yes',task('outcomes-2').answer));assert(checkAnswer('403',task('outcomes-4').answer));assert(task('inputs-9').answer.includes('[] и null rejected'));assert(task('outcomes-9').answer.includes('queued'));assert(task('reading-8').explanation.includes('Key retention не task retention'));
});
test('API retries are limited contracts, not equal responses or proof of no state change',()=>{
 for(const s of ['changes-1','changes-2','changes-3','test-a-7','test-a-8','test-b-7','test-b-8'])assert(checkAnswer('no',task(s).answer),s);assert(checkAnswer('409',task('changes-4').answer));assert(task('changes-5').answer.includes('24 h'));assert(task('changes-5').explanation.includes('concurrent'));assert(task('changes-8').answer.includes('representation can vary'));assert(task('changes-10').answer.includes('strict client'));assert(task('review-6').answer.includes('другой контракт'));
});
test('Cedar log distinguishes six attempts, three 201 responses, two creations and unknown timeout',()=>{
 assert.equal(words(apiReading),740);for(const [s,n]of [['reading-1','6'],['reading-2','2'],['reading-3','1.3']])assert(checkAnswer(n,task(s).answer));for(const phrase of ['exactly twenty-four hours','same account, method, path, key and identical JSON body','Rejections before creation do not reserve the key','three responses carried 201','only two creations are established','sixth outcome is unknown','older client rejects unknown response fields','No migration has been approved'])assert(apiReading.includes(phrase),phrase);assert(!checkAnswer('3',task('reading-2').answer));
});
test('Moss is an independent listening script with corrections, failed lookup body and limited commitments',()=>{
 assert.equal(words(apiListening),625);for(const [s,n]of [['listening-1','4'],['listening-2','2'],['listening-3','12']])assert(checkAnswer(n,task(s).answer));for(const phrase of ['two jobs had succeeded, one had failed','fifth submission timed out','within twelve hours'.replace('within','Within'),'same workspace, key and identical submission','Nothing has been released','not accepting responsibility for migrating','A successful lookup can report a failed export'])assert(apiListening.includes(phrase),phrase);assert(task('listening-4').answer.startsWith('Mina'));assert(task('listening-10').answer.includes('did not accept responsibility'));
});
test('Six full models are readable before answering; Rowan guide and full revision are separate tasks',()=>{
 assert.deepEqual(Object.values(apiModels).map(words),[326,178,102,106,107,322]);for(const model of Object.values(apiModels))assert(u.banks.find(b=>b.id==='writing').passage.includes(model));assert(u.banks.find(b=>b.id==='writing').passage.startsWith(apiBrief));assert(task('writing-2').prompt.includes('320–420'));assert(task('writing-9').prompt.includes('320–420'));assert(task('writing-9').explanation.includes('не готовый ответ Rowan'));assert(apiBrief.includes('null запрещён'));assert(apiBrief.includes('повтор после удаления даёт 404'));assert(task('review-7').answer.includes('partial update'));assert(!apiReading.includes('Rowan'));assert(!apiListening.includes('Cedar'));
});
test('New exams cover all goals with full production, five speech tasks and independent Alder/Brook constraints',()=>{
 const practicePrompts=new Set(u.banks.flatMap(b=>b.tasks.map(t=>t.prompt)));
 for(const e of u.tests){assert.equal(e.tasks.length,28);assert.equal(e.tasks.filter(isOpen).length,20);assert.equal(e.tasks.filter(t=>t.kind==='speech').length,5);for(const g of u.goals)assert(e.tasks.some(t=>t.goal===g.id));for(const t of e.tasks)assert(!practicePrompts.has(t.prompt));for(const n of [12,22])assert(e.tasks[n-1].prompt.includes('320–420'));assert(e.tasks[15].prompt.includes('Партнёр')||e.tasks[15].prompt.includes('партнёра'));assert(e.tasks[15].explanation.toLowerCase().includes('text-supported'));assert(e.tasks[25].prompt.includes('Через семь дней'));assert(e.tasks[25].explanation.includes('pending'));}
 assert(task('test-a-11').prompt.includes('15'));assert(task('test-b-9').answer.includes('nullable bio'));assert(task('test-b-10').answer.includes('B5 неизвестен'));assert(task('test-b-12').prompt.includes('preserve existing'));
});
test('API reference is bounded original practice supported by primary standards/guidance',()=>{
 assert.equal(apiPatterns.length,32);assert(apiPatterns.every(r=>r.length===4&&r.every(Boolean)));assert.equal(apiReference.practice.length,16);assert.deepEqual(apiSources.map(s=>new URL(s[1]).hostname),['www.rfc-editor.org','google.aip.dev']);assert(u.references.includes(apiReference.id));assert(apiReference.intro[1].includes('не гарантия для любого API'));
});
test('Earlier review export retains 121/365 steps, feedback, next draft, legacy archive, navigation and SRS',()=>{
 const s=earlier(),r=roundTrip(s);assert.deepEqual(r,s);assert(!r.learning[u.id]);assert.deepEqual(topicWorkProgress(r,'T03'),{kind:'expanded',completed:121,total:365,percent:33,practiceAnswered:120,practiceTotal:362,testsSubmitted:1,testsTotal:3});const before=structuredClone(r);unitState(r,u.id).answers[task('writing-2').id]='Synthetic guide\n'+apiModels.contract;assert.equal(topicWorkProgress(r,'T03').completed,122);assert.deepEqual(r.learning[first.id],before.learning[first.id]);assert.deepEqual(r.navigation,before.navigation);assert.deepEqual(r.bookmark,before.bookmark);assert.deepEqual(r.cards,before.cards);assert.deepEqual(roundTrip(r),r);
});
test('API multiline original, revision and unfinished exam persist separately without premature credit',()=>{
 const s=earlier(),p=unitState(s,u.id);p.answers[task('writing-2').id]='Synthetic original\n'+apiModels.contract;p.answers[task('writing-9').id]='Synthetic revision\n'+apiModels.revision;p.examDraft.answers[task('test-a-12').id]='Synthetic test draft\n'+apiModels.contract;assert.deepEqual(roundTrip(s),s);assert.equal(topicWorkProgress(s,'T03').completed,123);assert.equal(topicWorkProgress(s,'T03').testsSubmitted,1);
});
test('API A/B add one test step while all twenty open responses await substantive review',()=>{
 const s=earlier(),p=unitState(s,u.id);let original;for(const e of u.tests){p.examDraft.answers=Object.fromEntries(e.tasks.map(t=>[t.id,t.answer]));submitUnitTest(s,u.id,'2026-09-29T22:10:00Z');const score=scoreUnitTest(u,p.attempts.at(-1));assert.deepEqual([score.correct,score.total,score.pending,score.status],[8,8,20,'awaiting-review']);assert.equal(topicWorkProgress(s,'T03').completed,122);if(e.id==='a'){original=structuredClone(p.attempts[0]);startUnitTest(s,u.id);}else assert.deepEqual(p.attempts[0],original);}assert.deepEqual(roundTrip(s),s);
});
test('Earlier 242/365 steps remain intact without mastery and review requires actual audio acknowledgement, then delayed evidence',()=>{
 const s=earlier(),p=complete(s,u),attempt=p.attempts[0],speech=u.tests[0].tasks.find(t=>t.kind==='speech');assert.equal(topicWorkProgress(s,'T03').percent,66);assert.equal(topic.contentStatus,'expanded');attempt.reviews[speech.id]={score:3,reviewer:'Synthetic reviewer',date:'2026-09-29T22:15:00Z',evidence:'Synthetic fixture only.',heardAudio:false};assert.throws(()=>roundTrip(s),/прослушанное аудио/);for(const t of u.tests[0].tasks.filter(isOpen))attempt.reviews[t.id]={score:3,reviewer:'Synthetic reviewer',date:'2026-09-29T22:15:00Z',evidence:'Synthetic fixture only.',...(t.kind==='speech'?{heardAudio:true}:{})};assert.equal(scoreUnitTest(u,attempt).status,'awaiting-delayed-check');assert.deepEqual(roundTrip(s),s);const progress=topicWorkProgress(s,'T03');s.profile.minutes=10;assert.deepEqual(topicWorkProgress(s,'T03'),progress);
});
