import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {modules,courseStats,topicDevelopment} from '../data/course.mjs';
import {testingReading,testingListening,testingBrief,testingModels} from '../data/t03-testing-texts.mjs';
import {testingPatterns,testingReference,testingSources} from '../data/testing-language.mjs';
import {t03Vocabulary} from '../data/lexicon-t03.mjs';
import {freshState,unitState,validateState,checkAnswer,isOpen,submitUnitTest,startUnitTest,scoreUnitTest,topicWorkProgress,reviewCard,buildPlan} from '../web/engine.mjs';
import {questions,assessmentVersion} from '../data/assessment.mjs';
const topic=modules.find(m=>m.id==='T03'),u=topic.subtopics[2];
const all=[...u.banks.flatMap(b=>b.tasks),...u.tests.flatMap(e=>e.tasks)];
const task=s=>all.find(t=>t.id===u.id+'-'+s),words=s=>s.trim().split(/\s+/).length;
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const roundTrip=s=>validateState(JSON.parse(JSON.stringify(s)));
function complete(s,unit){const p=unitState(s,unit.id);for(const t of unit.banks.flatMap(b=>b.tasks))p.answers[t.id]=t.answer;p.examDraft.answers=Object.fromEntries(unit.tests[0].tasks.map(t=>[t.id,t.answer]));submitUnitTest(s,unit.id,'2026-09-30T10:00:00Z');return p;}
function earlier(){const s=freshState();s.moduleProgress.T03={selfChecked:true,date:'2026-09-22'};s.drafts.T03='Synthetic archive note\nNot learner work';s.cards['T03-v2']=reviewCard(null,'good',Date.UTC(2026,8,27));s.cards['T03-x-72']=reviewCard(null,'hard',Date.UTC(2026,8,29));for(const unit of topic.subtopics.slice(0,2)){const p=complete(s,unit);p.answers[unit.id+'-writing-2']='Synthetic original\n'+testingModels.plan;p.answers[unit.id+'-writing-9']='Synthetic revision\n'+testingModels.revision;p.attempts[0].reviews[unit.id+'-test-a-12']={score:3,reviewer:'Synthetic reviewer',date:'2026-09-30T10:01:00Z',evidence:'Fixture only, not a real learner result.'};startUnitTest(s,unit.id);p.examDraft.answers[unit.id+'-test-b-12']='Synthetic next draft\nStill unfinished';}s.navigation={current:'unit/T03-api/test',sections:{course:'unit/T03-api/test'},pages:{'unit/T03-api/test':{scroll:940,focus:'answer-T03-api-test-b-12',fields:{},details:[true]},'module/T03':{scroll:120,focus:'drill1',fields:{drill0:'returns',drill1:'writing\nOld answer',drill2:'edge'},details:[true]}}};s.bookmark={route:'unit/T03-api/test',scroll:940,focus:'answer-T03-api-test-b-12'};return s;}

test('Testing completes three populated T03 lines with substantial distinct banks, not a time limit',()=>{
 assert.equal(u.id,'T03-testing');assert.deepEqual(u.prerequisites,['T03-api']);assert.equal(u.explanation.length,15);assert.equal(u.explanation.reduce((n,e)=>n+e.text.length,0),11375);assert.equal(u.examples.length,36);assert.equal(u.goals.length,8);assert.deepEqual(u.banks.map(b=>b.tasks.length),[14,16,14,14,14,12,14,12,12]);assert.equal(topic.contentStatus,'expanded');assert.deepEqual(topic.remainingScope,[]);assert.equal(topicDevelopment.T03,undefined);assert.deepEqual(courseStats,{topics:40,expanded:38,partial:1,legacy:1,subtopics:123,practice:11157,testTasks:5432});
});
test('All published review/API tasks, tests, 72 cards and seven legacy cards remain byte-stable',()=>{
 const [review,api]=topic.subtopics;
 assert.equal(hash(review.banks),'e345375e62a69a924ed6b9303078e4340727939f1c35f126548f8ce8ac3bff56');assert.equal(hash(review.tests),'0547d49b972e021ff86216730b35052cc3169cd45799d69c6bd5a2ad01b0fd15');assert.equal(hash(api.banks),'d1734fbce2704f1fc80816d76a75ebbf36e7cef928513f3f7c9ed6f320db5358');assert.equal(hash(api.tests),'a30ac4f7e7660df5d3e52de1cd69cc1243140d88b0cb0eaa7b38cb999c586ec7');assert.equal(hash(t03Vocabulary.slice(0,72)),'6c1051ad32ab268283a4ad556f6214541cfb5c20d3778841bac39ce73f54dc59');assert.equal(hash(topic.vocabulary.filter(c=>!/^T03-x-\d+$/.test(c.id))),'60d23d41faed329d6ea2f8df5e0104c8c770ef3e57b5327e310110ce5ffe85a3');
});
test('Testing cards append stable IDs, UK IPA, contexts and idiomatic chunks without duplicates',()=>{
 assert.equal(t03Vocabulary.length,108);assert.equal(t03Vocabulary[72].id,'T03-x-73');assert.equal(t03Vocabulary.at(-1).id,'T03-x-108');assert.equal(topic.vocabulary.length,115);assert.equal(new Set(topic.vocabulary.map(c=>c.word)).size,115);for(const c of t03Vocabulary.slice(72))assert(c.context&&c.note&&c.accent==='UK'&&/^\/.+\/$/.test(c.ipa));for(const word of ['pin down','carry over','crop up'])assert(t03Vocabulary.some(c=>c.word===word&&c.kind==='фразовый глагол'));
});
test('Testing grammar has independent right/wrong keys and manually evaluated complete sentences',()=>{
 for(const [s,right,wrong]of [['forms-1','preserves','preserve'],['forms-2','check','checks'],['forms-3','ran','run'],['forms-4','run','ran'],['forms-5','be','is'],['forms-6','exist','will exist'],['forms-7','fails','does fail'],['forms-8','least','most'],['test-a-1','rejects','reject'],['test-a-2','run','ran'],['test-a-3','fails','does fail'],['test-a-4','be','is'],['test-b-1','compare','compares'],['test-b-2','ran','run'],['test-b-3','most','least'],['test-b-4','is','will be']]){assert(!isOpen(task(s)));assert(checkAnswer(right,task(s).answer),s);assert(!checkAnswer(wrong,task(s).answer),s);}
 assert(task('forms-7').prompt.includes('без усиления'));assert(isOpen(task('forms-10')));assert(isOpen(task('test-a-18')));assert(isOpen(task('test-b-18')));
});
test('Cases distinguish inclusive boundaries, enough data, valid rejection and unspecified duplicates',()=>{
 for(const [s,right,wrong]of [['cases-1','1','0'],['cases-2','20','21'],['cases-3','0','1'],['cases-4','21','20'],['assertions-2','20','19'],['assertions-3','19','20']]){assert(checkAnswer(right,task(s).answer));assert(!checkAnswer(wrong,task(s).answer));}
 assert(task('cases-5').answer.includes('22 completed and 3 incomplete'));assert(task('cases-7').answer.includes('empty list'));assert(task('cases-11').answer.includes('does not establish'));assert(task('cases-14').answer.includes('2 and 8'));assert(task('cases-16').answer.includes('source unchanged missing assertion'));
});
test('Assertions separate container type, exact output, independent expectations and unchanged source',()=>{
 for(const s of ['assertions-1','assertions-4','test-a-6','test-b-6'])assert(checkAnswer('no',task(s).answer));assert(task('assertions-7').answer.includes('independently'));assert(task('assertions-8').answer.includes('independent representation'));assert(task('assertions-9').explanation.includes('expected'));assert(task('assertions-11').answer.includes('D8'));assert(task('assertions-12').answer.includes('still needs agreement'));
});
test('Fern reading preserves first batch, later repeats, assertion limits, metric and ownership',()=>{
 assert.equal(words(testingReading),700);for(const phrase of ['six executed cases: five passed and one failed','eighteen of twenty instrumented statements','eight execution attempts across six distinct executed cases','twenty-two completed items followed by three incomplete items','source-unchanged requirement was not asserted','One repeat fails with nineteen','other passes with twenty'])assert(testingReading.includes(phrase),phrase);
 for(const [s,right,wrong]of [['reading-1','260','2.6'],['reading-2','22','25'],['reading-3','6','8'],['results-1','6','8'],['results-2','5','6'],['results-3','8','6']]){assert(checkAnswer(right,task(s).answer));assert(!checkAnswer(wrong,task(s).answer));}assert(checkAnswer('no',task('results-4').answer));assert(task('reading-8').explanation.includes('девятый'));assert(task('reading-12').answer.includes('no accepted credential ownership'));
});
test('Larch audio is distinct with actual correction, failed identifier, two passes and unimplemented draft',()=>{
 assert.equal(words(testingListening),597);assert(!testingListening.includes('Fern'));for(const phrase of ['Three were executed','document D8','were D9','Both extra switch runs passed','five execution attempts across three executed cases','I have drafted a replacement assertion in my notes','I have not changed the shared test','agree that condition precisely','not whether the right document was asserted'])assert(testingListening.includes(phrase),phrase);
 assert.equal(u.banks.find(b=>b.id==='listening').kind,'listening');assert(task('listening-4').answer.includes('performance threshold'));assert(task('listening-9').answer.includes('Review wording only'));assert(task('listening-12').explanation.includes('audio evidence'));
});
test('Six full models precede independent Maple original and full revision with different rules',()=>{
 assert.deepEqual(Object.values(testingModels).map(words),[336,201,106,103,109,325]);const writing=u.banks.find(b=>b.id==='writing');assert(writing.passage.startsWith(testingBrief));for(const m of Object.values(testingModels))assert(writing.passage.includes(m));for(const n of [2,9])assert(task('writing-'+n).prompt.includes('320–420'));assert(task('writing-9').explanation.includes('pending'));assert(testingBrief.includes('ABCDEFGHIJKL'));assert(testingBrief.includes('16/20'));assert(testingBrief.includes('шесть executions пяти cases'));assert(!testingReading.includes('Maple'));assert(task('writing-4').answer.includes('four passed'));assert(task('writing-7').answer.includes('Six executions'));
});
test('Two new exams cover all goals with eight closed, twenty manual and five actual speech tasks each',()=>{
 const seen=new Set(u.banks.flatMap(b=>b.tasks.map(t=>t.prompt)));
 for(const e of u.tests){assert.equal(e.tasks.length,28);assert.equal(e.tasks.filter(isOpen).length,20);assert.equal(e.tasks.filter(t=>t.kind==='speech').length,5);for(const g of u.goals)assert(e.tasks.some(t=>t.goal===g.id));for(const t of e.tasks){assert(!seen.has(t.prompt));seen.add(t.prompt);}for(const n of [12,22])assert(e.tasks[n-1].prompt.includes('320–420'));assert(e.tasks[14].explanation.includes('text-supported'));assert(e.tasks[25].prompt.includes('Через семь дней'));assert(e.tasks[25].explanation.includes('pending'));}
 assert(task('test-a-9').prompt.includes('Duplicate identifiers должны отвергаться'));assert(task('test-a-11').answer.includes('seven attempts/five cases'));assert(task('test-a-12').answer.includes('75%'));assert(task('test-b-9').answer.includes('empty is valid'));assert(task('test-b-11').answer.includes('both R3-case runs failed'));assert(task('test-b-12').answer.includes('70% branch'));assert(task('test-b-24').answer.includes('[1,1,3]'));
});
test('Testing reference offers 32 models and 16 original exercises with bounded primary guidance',()=>{
 assert.equal(testingPatterns.length,32);assert(testingPatterns.every(r=>r.length===4&&r.every(Boolean)));assert.equal(testingReference.practice.length,16);assert.deepEqual(testingSources.map(s=>new URL(s[1]).hostname),['playwright.dev','playwright.dev','testing.googleblog.com']);assert(u.references.includes(testingReference.id));assert(testingReference.intro[1].includes('не универсальная настройка'));assert(testingReference.intro[2].includes('unknown'));
});
test('Import preserves two earlier units at 242/365, originals, revisions, reviews, next drafts and all archived state',()=>{
 const s=earlier(),r=roundTrip(s);assert.deepEqual(r,s);assert(!r.learning[u.id]);assert.deepEqual(topicWorkProgress(r,'T03'),{kind:'expanded',completed:242,total:365,percent:66,practiceAnswered:240,practiceTotal:362,testsSubmitted:2,testsTotal:3});const before=structuredClone(r);unitState(r,u.id).answers[task('writing-2').id]='Synthetic Maple original\n'+testingModels.plan;assert.equal(topicWorkProgress(r,'T03').completed,243);for(const unit of topic.subtopics.slice(0,2))assert.deepEqual(r.learning[unit.id],before.learning[unit.id]);for(const key of ['navigation','bookmark','cards','drafts','moduleProgress'])assert.deepEqual(r[key],before[key]);assert.deepEqual(roundTrip(r),r);
});
test('First-unit-only work now remains 121/365, not reset or inflated by old self-check',()=>{
 const s=earlier();delete s.learning['T03-api'];assert.deepEqual([topicWorkProgress(s,'T03').completed,topicWorkProgress(s,'T03').percent],[121,33]);const old=freshState();old.moduleProgress.T03={selfChecked:true,date:'2026-09-22'};assert.equal(topicWorkProgress(roundTrip(old),'T03').completed,0);assert(!roundTrip(old).learning[u.id]);
});
test('Testing multiline original, revision and interrupted exam preserve independent fields without premature test credit',()=>{
 const s=earlier(),p=unitState(s,u.id);p.answers[task('writing-2').id]='Synthetic original\n'+testingModels.plan;p.answers[task('writing-9').id]='Synthetic revision\n'+testingModels.revision;p.examDraft.answers[task('test-a-12').id]='Synthetic test draft\n'+testingModels.plan;assert.deepEqual(roundTrip(s),s);assert.equal(topicWorkProgress(s,'T03').completed,244);assert.equal(topicWorkProgress(s,'T03').testsSubmitted,2);
});
test('Both testing variants contribute one test step, retain history and require twenty manual reviews',()=>{
 const s=earlier(),p=unitState(s,u.id);let original;for(const e of u.tests){p.examDraft.answers=Object.fromEntries(e.tasks.map(t=>[t.id,t.answer]));submitUnitTest(s,u.id,'2026-09-30T10:10:00Z');const score=scoreUnitTest(u,p.attempts.at(-1));assert.deepEqual([score.correct,score.total,score.pending,score.status],[8,8,20,'awaiting-review']);assert.equal(topicWorkProgress(s,'T03').completed,243);if(e.id==='a'){original=structuredClone(p.attempts[0]);startUnitTest(s,u.id);}else assert.deepEqual(p.attempts[0],original);}assert.deepEqual(roundTrip(s),s);
});
test('Even all 365 work steps and expanded publication require real-audio review and later transfer, independent of minutes',()=>{
 const s=earlier(),p=complete(s,u),attempt=p.attempts[0],speech=u.tests[0].tasks.find(t=>t.kind==='speech');assert.equal(topicWorkProgress(s,'T03').percent,100);assert.equal(topicWorkProgress(s,'T03').completed,365);assert.equal(scoreUnitTest(u,attempt).status,'awaiting-review');attempt.reviews[speech.id]={score:3,reviewer:'Synthetic reviewer',date:'2026-09-30T10:15:00Z',evidence:'Fixture only.',heardAudio:false};assert.throws(()=>roundTrip(s),/прослушанное аудио/);for(const t of u.tests[0].tasks.filter(isOpen))attempt.reviews[t.id]={score:3,reviewer:'Synthetic reviewer',date:'2026-09-30T10:15:00Z',evidence:'Fixture only.',...(t.kind==='speech'?{heardAudio:true}:{})};assert.equal(scoreUnitTest(u,attempt).status,'awaiting-delayed-check');assert.deepEqual(roundTrip(s),s);s.placement={assessmentVersion,date:'2026-09-30T10:30:00Z',answers:Object.fromEntries(questions.map(q=>[q.id,q.options.length]))};assert(buildPlan(s).items.some(m=>m.id==='T03'&&m.contentStatus==='expanded'));const work=topicWorkProgress(s,'T03');s.profile.minutes=10;s.profile.days=2;assert.deepEqual(topicWorkProgress(s,'T03'),work);
});
