import {mkdir, writeFile} from 'node:fs/promises';
import {modules} from '../data/course.mjs';
const root=new URL('../course/',import.meta.url);
await mkdir(new URL('modules/',root),{recursive:true});
const list=items=>items.map(s=>'- '+s).join('\n');
for(const m of modules){
  const content=`# ${m.id} · ${m.level} · ${m.title}\n\nСгенерировано из data/*.mjs; изменения вносить в источник.\n\nТемы: ${m.focus}.\nПредпосылки: ${m.prerequisites.join(', ')||'нет'}. Базовый цикл: ${m.sessions} занятий, с продлением по результатам.\n\n## Объяснение\n\n${m.rule}\n\n## Примеры: от простого к сложному\n\n${list(m.examples)}\n\n## Чтение\n\n${m.reading[0]}\n\nВопрос: ${m.reading[1]}\n\n## Аудирование\n\nСначала слушайте в приложении, не открывая текст. Два прослушивания: общий смысл, затем детали.\n\nВопрос: ${m.listening[1]}\n\n<details><summary>Транскрипт — после попытки</summary>\n\n${m.listening[0]}\n\n</details>\n\n## Упражнения\n\n${m.drills.map((d,i)=>`${i+1}. ${d[0]}`).join('\n')}\n\n## Словарь в контексте\n\n${list(m.vocabulary.map(v=>`${v.word} — ${v.translation}; ${v.context}`))}\n\n## Письмо\n\n${m.write}\n\n## Речь и взаимодействие\n\n${m.speak}\n\n## Произношение\n\n${m.sound}\n\n## Проверка и усложнение\n\nЗакрой примеры и создай 5 своих предложений. Затем измени время, адресата или условие: объясни, как меняется смысл. Попроси агента дать 5 новых задач и неожиданный уточняющий вопрос. Через 7 дней повтори на другом материале. Критерии — [TEACHING.md](../TEACHING.md) и [рубрика](../../assessment/RUBRICS.md).\n\n## Ключи\n\n<details><summary>Открыть после ответа</summary>\n\nЧтение: ${m.reading[2]}\n\nАудирование: ${m.listening[2]}\n\n${m.drills.map((d,i)=>`${i+1}. ${d[1].replaceAll('|',' / ')} — ${d[2]}`).join('\n')}\n\nОткрытые задания не имеют единственной формулировки. Образцы выше показывают конструкции; оценка письма и речи требует разбора вашего ответа.\n\n</details>\n\nГрамматический справочник: [карта Murphy/Hewings](../../library/MURPHY.md).\n`;
  await writeFile(new URL(`modules/${m.id}.md`,root),content,'utf8');
}
await writeFile(new URL('INDEX.md',root),`# Полный курс\n\n${modules.length} интегрированных модулей. Каждый объединяет объяснение, примеры, упражнения, чтение, аудирование, письмо, речь, произношение и словарь. Пять 30-минутных занятий — исходный цикл, а не гарантированный срок освоения.\n\n| Модуль | Уровень | Тема |\n|---|---|---|\n${modules.map(m=>`| [${m.id}](modules/${m.id}.md) | ${m.level} | ${m.title} |`).join('\n')}\n`,'utf8');
console.log(`Built ${modules.length} module documents and course index.`);
