import assert from 'node:assert/strict';

// Isolated synthetic data only; no learner profile or real speech service.
export async function checkT04({evaluate,route,command,poll,screenshot,delay,importSynthetic}){
 const fill=async(selector,value)=>evaluate(`{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));}`);
 await command('Emulation.setDeviceMetricsOverride',{width:1365,height:1000,deviceScaleFactor:1,mobile:false});
 await route('settings','#profile');
 await evaluate(`(async()=>{const {freshState,reviewCard}=await import('/engine.mjs');const {questions,assessmentVersion}=await import('/data/assessment.mjs');const s=freshState();s.moduleProgress.T04={selfChecked:true,date:'2026-09-22'};s.drafts.T04='Synthetic old T04 notes.\\nNot learner data.';s.cards['T04-v2']=reviewCard(null,'good',Date.UTC(2026,8,27));s.cards['T04-x-roll-back']=reviewCard(null,'hard',Date.UTC(2026,8,27));s.navigation.pages['module/T04']={scroll:240,focus:'drill1',fields:{drill0:'throughput',drill1:'compatibility\\nSynthetic original answer',drill2:'would'},details:[]};s.placement={assessmentVersion,date:'2026-09-29T21:30:00Z',answers:Object.fromEntries(questions.map(q=>[q.id,q.options.length]))};s.bookmark={route:'module/T04',scroll:240,focus:'drill1'};s.navigation.sections.course='module/T04';window.__t04Original=JSON.stringify(s);})()`);
 const original=await evaluate('window.__t04Original');await importSynthetic('window.__t04Original');
 await route('module/T04','#legacy-practice');assert.equal(await evaluate('document.querySelectorAll(".unit-card").length'),1);assert.equal(await evaluate('document.querySelector(".topic-progress progress").max'),127);assert.equal(await evaluate('document.querySelector(".topic-progress progress").value'),0);
 assert.equal(await evaluate('document.querySelector("#drill1").value'),'compatibility\nSynthetic original answer');assert(await evaluate('document.querySelector("#drill1").readOnly'));assert.equal(await evaluate('document.querySelector("#draft").value'),'Synthetic old T04 notes.\nNot learner data.');
 assert((await evaluate('document.querySelector("#topic-development").textContent')).includes('миграция'));assert((await evaluate('document.querySelector(".topic-progress").textContent')).includes('Прогресс опубликованной части'));
 await evaluate('document.querySelector("#legacy-practice").open=true');await route('home','.hero');await route('module/T04','#legacy-practice');await command('Page.reload');await poll(()=>evaluate('document.querySelector("#drill2")?.value==="would"'),'T04 old archive persists');
 const u=await evaluate(`(async()=>{const {subtopics}=await import('/data/course.mjs');return subtopics.find(u=>u.id==='T04-decisions')})()`);
 await route('unit/T04-decisions/explain','#unit-content');await screenshot('t04-decisions-explain-desktop.png');assert((await evaluate('document.querySelector(".topic-progress").textContent')).includes('Прогресс опубликованной части'));
 await route('unit/T04-decisions/examples','#unit-content');assert(await evaluate('document.querySelector("#unit-content").textContent.length>2000'));
 for(const b of u.banks){
  await route('unit/T04-decisions/'+b.id,'#check-bank');assert.equal(await evaluate('document.querySelectorAll("[data-task]").length'),b.tasks.length);assert(await evaluate('new Set([...document.querySelectorAll("[id]")].map(n=>n.id)).size===document.querySelectorAll("[id]").length'));
  if(b.id==='forms'){
   await fill('#answer-T04-decisions-forms-1','to retain');await evaluate('document.querySelector("#check-bank").click()');assert(!(await evaluate('document.querySelector("#feedback-T04-decisions-forms-1").textContent')).startsWith('Верно'));
   await fill('#answer-T04-decisions-forms-1','retain');await evaluate('document.querySelector("#check-bank").click()');assert((await evaluate('document.querySelector("#feedback-T04-decisions-forms-1").textContent')).startsWith('Верно'));
  }
  if(b.id==='reading')assert((await evaluate('document.querySelector(".reading").textContent')).includes('decision record 14 remains Proposed'));
  if(b.id==='writing'){assert((await evaluate('document.querySelector(".reading").textContent')).includes('ADR 14: investigate queued exports'));assert((await evaluate('document.querySelector(".reading").textContent')).includes('Revised ADR 14: compare queued exports'));assert(await evaluate('[...document.querySelectorAll("[data-task]")].every(el=>!el.value)'));}
  if(b.kind==='listening'){
   assert(!(await evaluate('document.querySelector("#unit-content").textContent')).includes(b.passage.slice(0,60)));
   await evaluate(`{const answers=${JSON.stringify(Object.fromEntries(b.tasks.map(t=>[t.id,t.answer.split('|')[0]])))};for(const el of document.querySelectorAll('[data-task]')){el.value=answers[el.dataset.task];el.dispatchEvent(new Event('input',{bubbles:true}));}document.querySelector('#check-bank').click();}`);
   assert((await evaluate('document.querySelector("#bank-transcript").textContent')).includes('Four of five'));
  }
 }
 const models=await evaluate(`(async()=>{const {decisionModels}=await import('/data/t04-decisions-texts.mjs');return decisionModels})()`),full='Synthetic original, not learner work.\n'+models.record,revised='Synthetic full revision, not learner work.\n'+models.revision;
 await route('unit/T04-decisions/writing','#check-bank');await fill('#answer-T04-decisions-writing-2',full);await fill('#answer-T04-decisions-writing-9',revised);await command('Page.reload');await poll(()=>evaluate(`document.querySelector('#answer-T04-decisions-writing-2')?.value===${JSON.stringify(full)}`),'T04 full ADR persists');
 await route('home','.hero');await evaluate('document.querySelector("aside a[data-section=course]").click()');await poll(()=>evaluate(`document.querySelector('#answer-T04-decisions-writing-9')?.value===${JSON.stringify(revised)}`),'T04 nested route and full revision persist');
 await route('unit/T04-decisions/test','#unit-test');assert.equal(await evaluate('document.querySelectorAll(".answer-review").length'),0);await fill('#answer-T04-decisions-test-a-12',full);await command('Page.reload');await poll(()=>evaluate(`document.querySelector('#answer-T04-decisions-test-a-12')?.value===${JSON.stringify(full)}`),'T04 long exam draft persists');
 for(const [i,e]of u.tests.entries()){
  assert.equal(await evaluate('document.querySelectorAll("[data-task]").length'),28);
  await evaluate(`{const answers=${JSON.stringify(Object.fromEntries(e.tasks.map(t=>[t.id,t.answer.split('|')[0]])))};for(const el of document.querySelectorAll('[data-task]')){el.value=answers[el.dataset.task];el.dispatchEvent(new Event('input',{bubbles:true}));}document.querySelector('#unit-test').requestSubmit();}`);
  assert.equal(await evaluate('document.querySelectorAll(".answer-review").length'),28*(i+1));assert.equal(await evaluate('document.querySelectorAll("[data-review]").length'),20*(i+1));assert((await evaluate('document.querySelector("#test-history").textContent')).includes('Ожидает содержательной проверки'));
  if(!i){await evaluate('document.querySelector("#new-unit-test").click()');assert((await evaluate('document.querySelector("#unit-content h3").textContent')).includes('B'));}
 }
 await route('module/T04','#legacy-practice');assert.equal(await evaluate('document.querySelector(".topic-progress progress").value'),16,'15 practice answers + one submitted test, no credit for old self-check or repeated variants');
 await route('references/architecture-decisions','#reference-search');assert.equal(await evaluate('document.querySelectorAll("#reference-rows tr").length'),32);await fill('#reference-search','estimate');const filtered=await evaluate('document.querySelectorAll("#reference-rows tr").length');assert(filtered>0&&filtered<32);await route('home','.hero');await evaluate('document.querySelector("aside a[data-section=references]").click()');await poll(()=>evaluate('document.querySelector("#reference-search")?.value==="estimate"'),'T04 reference filter persists');await fill('#reference-search','');
 await delay(9100);await command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 for(const [path,selector,name]of [['module/T04','#legacy-practice','topic'],['unit/T04-decisions/reading','#check-bank','reading'],['unit/T04-decisions/writing','#check-bank','writing'],['unit/T04-decisions/speaking','#check-bank','speaking'],['references/architecture-decisions','#reference-search','reference']]){
  await route(path,selector);assert(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),'T04 mobile overflow '+path);if(name==='writing')await evaluate('document.querySelector("textarea[data-task]").closest(".task").scrollIntoView({block:"start"})');if(name==='reference')await evaluate('document.querySelector(".table-wrap").scrollIntoView({block:"start"})');await screenshot('t04-'+name+'-mobile.png');
 }
 await route('settings','#profile');await evaluate(`(async()=>{const s=JSON.parse(localStorage.getItem('english-training-v1'));const {subtopics}=await import('/data/course.mjs');const {validateState}=await import('/engine.mjs');for(const t of subtopics.find(u=>u.id==='T04-decisions').banks.flatMap(b=>b.tasks))s.learning['T04-decisions'].answers[t.id]=t.answer;window.__t04Complete=JSON.stringify(validateState(s));})()`);
 await importSynthetic('window.__t04Complete');await route('module/T04','#legacy-practice');assert.equal(await evaluate('document.querySelector(".topic-progress progress").value'),127);assert.equal(await evaluate('document.querySelector(".topic-progress progress").max'),127);await command('Page.reload');await poll(()=>evaluate('document.querySelector(".topic-progress progress")?.value===127'),'T04 complete published work persists');
 assert((await evaluate('document.querySelector(".topic-progress").textContent')).includes('100% не означает завершение всего топика или освоение'));assert((await evaluate('document.querySelector("#topic-development").textContent')).includes('миграция'));
 await route('course','#module-list');assert((await evaluate('[...document.querySelectorAll(".module-row")].find(n=>n.textContent.includes("T04")).textContent')).includes('Прогресс опубликованной части'));
 await route('plan','[data-topic-progress="T04"]');assert((await evaluate('document.querySelector("[data-topic-progress=T04]").textContent')).includes('Прогресс опубликованной части'));
 await route('home','.hero');assert((await evaluate('document.querySelector("main").textContent')).includes('Частично опубликовано: 1'));
 await evaluate(`{const s=JSON.parse(localStorage.getItem('english-training-v1')),old=JSON.parse(${JSON.stringify(original)});if(JSON.stringify(s.cards)!==JSON.stringify(old.cards))throw Error('Changed old T04 SRS');if(JSON.stringify(s.navigation.pages['module/T04'].fields)!==JSON.stringify(old.navigation.pages['module/T04'].fields))throw Error('Lost T04 archive');if(s.learning['T04-decisions'].attempts.length!==2)throw Error('Lost T04 history');if(s.drafts.T04!==old.drafts.T04)throw Error('Lost T04 old notes');}`);
 console.log('T04 smoke passed: nine banks, A/B exams, full original/revised ADRs, 0→16→127 decision steps preserved within 127, old archive/SRS, nested drafts, reference and mobile.');
}
