import assert from 'node:assert/strict';

// Synthetic isolated fixture only. No learner data and no real speech service.
export async function checkT05({evaluate,route,command,poll,screenshot,delay,importSynthetic}){
 const fill=async(selector,value)=>evaluate(`{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));}`);
 const progress=()=>evaluate(`{const p=document.querySelector('.topic-progress progress');({value:p.value,max:p.max})}`);
 await command('Emulation.setDeviceMetricsOverride',{width:1365,height:1000,deviceScaleFactor:1,mobile:false});
 await route('settings','#profile');
 await evaluate(`(async()=>{const {freshState,reviewCard}=await import('/engine.mjs');const {questions,assessmentVersion}=await import('/data/assessment.mjs');const s=freshState();s.moduleProgress.T05={selfChecked:true,date:'2026-09-22'};s.drafts.T05='Synthetic old T05 notes.\\nNot learner data.';s.cards['T05-v2']=reviewCard(null,'good',Date.UTC(2026,8,27));s.cards['T05-x-root-cause']=reviewCard(null,'hard',Date.UTC(2026,8,27));s.navigation.pages['module/T05']={scroll:240,focus:'drill1',fields:{drill0:'authorization',drill1:'confirmed\\nSynthetic original answer',drill2:'with'},details:[]};s.placement={assessmentVersion,date:'2026-10-02T10:30:00Z',answers:Object.fromEntries(questions.map(q=>[q.id,q.options.length]))};s.bookmark={route:'module/T05',scroll:240,focus:'drill1'};s.navigation.sections.course='module/T05';window.__t05Original=JSON.stringify(s);})()`);
 const original=await evaluate('window.__t05Original');await importSynthetic('window.__t05Original');
 await route('module/T05','#legacy-practice');assert.equal(await evaluate('document.querySelectorAll(".unit-card").length'),1);assert.deepEqual(await progress(),{value:0,max:127});
 assert.equal(await evaluate('document.querySelector("#drill1").value'),'confirmed\nSynthetic original answer');assert(await evaluate('document.querySelector("#drill1").readOnly'));assert.equal(await evaluate('document.querySelector("#draft").value'),'Synthetic old T05 notes.\nNot learner data.');
 assert((await evaluate('document.querySelector("#topic-development").textContent')).includes('Postmortem'));assert((await evaluate('document.querySelector(".topic-progress").textContent')).includes('Прогресс опубликованной части'));
 await evaluate('document.querySelector("#legacy-practice").open=true');await route('home','.hero');await route('module/T05','#legacy-practice');await command('Page.reload');await poll(()=>evaluate('document.querySelector("#drill2")?.value==="with"'),'T05 legacy archive persists');
 const u=await evaluate(`(async()=>{const {subtopics}=await import('/data/course.mjs');return subtopics.find(u=>u.id==='T05-incidents')})()`);
 await route('unit/T05-incidents/explain','#unit-content');await screenshot('t05-incidents-explain-desktop.png');
 await route('unit/T05-incidents/examples','#unit-content');assert(await evaluate('document.querySelector("#unit-content").textContent.length>2000'));
 for(const b of u.banks){
  await route('unit/T05-incidents/'+b.id,'#check-bank');assert.equal(await evaluate('document.querySelectorAll("[data-task]").length'),b.tasks.length);assert(await evaluate('new Set([...document.querySelectorAll("[id]")].map(n=>n.id)).size===document.querySelectorAll("[id]").length'));
  if(b.id==='forms'){
   await fill('#answer-T05-incidents-forms-1','have');await evaluate('document.querySelector("#check-bank").click()');assert(!(await evaluate('document.querySelector("#feedback-T05-incidents-forms-1").textContent')).startsWith('Верно'));
   await fill('#answer-T05-incidents-forms-1','are');await evaluate('document.querySelector("#check-bank").click()');assert((await evaluate('document.querySelector("#feedback-T05-incidents-forms-1").textContent')).startsWith('Верно'));
  }
  if(b.id==='reading')assert((await evaluate('document.querySelector(".reading").textContent')).includes('Orchard Exports 4.2'));
  if(b.id==='writing'){const text=await evaluate('document.querySelector(".reading").textContent');assert(text.includes('Hawthorn Search 2.8'));assert(text.includes('Orchard exercise 18: internal handover'));assert(text.includes('Revised Orchard handover'));assert(await evaluate('[...document.querySelectorAll("[data-task]")].every(el=>!el.value)'));}
  if(b.kind==='listening'){
   assert(!(await evaluate('document.querySelector("#unit-content").textContent')).includes(b.passage.slice(0,60)));
   await evaluate(`{const answers=${JSON.stringify(Object.fromEntries(b.tasks.map(t=>[t.id,t.answer.split('|')[0]])))};for(const el of document.querySelectorAll('[data-task]')){el.value=answers[el.dataset.task];el.dispatchEvent(new Event('input',{bubbles:true}));}document.querySelector('#check-bank').click();}`);
   assert((await evaluate('document.querySelector("#bank-transcript").textContent')).includes('fifteen oh four'));
  }
 }
 const models=await evaluate(`(async()=>{const {incidentModels}=await import('/data/t05-incidents-texts.mjs');return incidentModels})()`),full='Synthetic original, not learner work.\n'+models.report,revised='Synthetic full revision, not learner work.\n'+models.revision;
 await route('unit/T05-incidents/writing','#check-bank');await fill('#answer-T05-incidents-writing-2',full);await fill('#answer-T05-incidents-writing-9',revised);await command('Page.reload');await poll(()=>evaluate(`document.querySelector('#answer-T05-incidents-writing-2')?.value===${JSON.stringify(full)}`),'T05 long original persists');
 await route('home','.hero');await evaluate('document.querySelector("aside a[data-section=course]").click()');await poll(()=>evaluate(`document.querySelector('#answer-T05-incidents-writing-9')?.value===${JSON.stringify(revised)}`),'T05 nested writing path and revision persist');
 await route('unit/T05-incidents/test','#unit-test');assert.equal(await evaluate('document.querySelectorAll(".answer-review").length'),0);await fill('#answer-T05-incidents-test-a-14',full);await command('Page.reload');await poll(()=>evaluate(`document.querySelector('#answer-T05-incidents-test-a-14')?.value===${JSON.stringify(full)}`),'T05 long exam draft persists without keys');
 for(const [i,e]of u.tests.entries()){
  assert.equal(await evaluate('document.querySelectorAll("[data-task]").length'),30);
  await evaluate(`{const answers=${JSON.stringify(Object.fromEntries(e.tasks.map(t=>[t.id,t.answer.split('|')[0]])))};for(const el of document.querySelectorAll('[data-task]')){el.value=answers[el.dataset.task];el.dispatchEvent(new Event('input',{bubbles:true}));}document.querySelector('#unit-test').requestSubmit();}`);
  assert.equal(await evaluate('document.querySelectorAll(".answer-review").length'),30*(i+1));assert.equal(await evaluate('document.querySelectorAll("[data-review]").length'),20*(i+1));assert((await evaluate('document.querySelector("#test-history").textContent')).includes('Ожидает содержательной проверки'));
  if(!i){await evaluate('document.querySelector("#new-unit-test").click()');assert((await evaluate('document.querySelector("#unit-content h3").textContent')).includes('B'));}
 }
 await route('module/T05','#legacy-practice');assert.deepEqual(await progress(),{value:16,max:127},'15 practice answers and one test; no old-check or second-test credit');
 await route('references/incident-language','#reference-search');assert.equal(await evaluate('document.querySelectorAll("#reference-rows tr").length'),32);await fill('#reference-search','handover');const filtered=await evaluate('document.querySelectorAll("#reference-rows tr").length');assert(filtered>0&&filtered<32);await route('home','.hero');await evaluate('document.querySelector("aside a[data-section=references]").click()');await poll(()=>evaluate('document.querySelector("#reference-search")?.value==="handover"'),'T05 reference search persists');await fill('#reference-search','');
 await delay(9100);await command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 for(const [path,selector,name]of [['module/T05','#legacy-practice','topic'],['unit/T05-incidents/reading','#check-bank','reading'],['unit/T05-incidents/writing','#check-bank','writing'],['unit/T05-incidents/speaking','#check-bank','speaking'],['references/incident-language','#reference-search','reference']]){
  await route(path,selector);assert(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),'T05 mobile overflow '+path);if(name==='writing')await evaluate('document.querySelector("textarea[data-task]").closest(".task").scrollIntoView({block:"start"})');if(name==='reference')await evaluate('document.querySelector(".table-wrap").scrollIntoView({block:"start"})');await screenshot('t05-'+name+'-mobile.png');
 }
 await route('settings','#profile');await evaluate(`(async()=>{const s=JSON.parse(localStorage.getItem('english-training-v1'));const {subtopics}=await import('/data/course.mjs');const {validateState,startUnitTest}=await import('/engine.mjs');const p=s.learning['T05-incidents'];for(const t of subtopics.find(u=>u.id==='T05-incidents').banks.flatMap(b=>b.tasks))p.answers[t.id]=t.answer;p.answers['T05-incidents-writing-2']=${JSON.stringify(full)};p.answers['T05-incidents-writing-9']=${JSON.stringify(revised)};p.attempts[0].reviews['T05-incidents-test-a-14']={score:3,reviewer:'Synthetic reviewer',date:'2026-10-02T13:00:00Z',evidence:'Fixture only; not learner data.'};startUnitTest(s,'T05-incidents');p.examDraft.answers['T05-incidents-test-a-14']='Synthetic next unfinished draft\\nNot submitted';window.__t05Complete=JSON.stringify(validateState(s));})()`);
 await importSynthetic('window.__t05Complete');await route('module/T05','#legacy-practice');assert.deepEqual(await progress(),{value:127,max:127});await command('Page.reload');await poll(()=>evaluate('document.querySelector(".topic-progress progress")?.value===127'),'T05 complete published work persists');
 assert((await evaluate('document.querySelector(".topic-progress").textContent')).includes('100% не означает завершение всего топика или освоение'));assert((await evaluate('document.querySelector("#topic-development").textContent')).includes('Безопасность'));
 await route('course','#module-list');assert((await evaluate('[...document.querySelectorAll(".module-row")].find(n=>n.textContent.includes("T05")).textContent')).includes('Прогресс опубликованной части'));
 await route('plan','[data-topic-progress="T05"]');assert((await evaluate('document.querySelector("[data-topic-progress=T05]").textContent')).includes('Прогресс опубликованной части'));
 await route('home','.hero');assert((await evaluate('document.querySelector("main").textContent')).includes('Частично опубликовано: 1'));
 await evaluate(`{const s=JSON.parse(localStorage.getItem('english-training-v1')),old=JSON.parse(${JSON.stringify(original)});if(JSON.stringify(s.cards)!==JSON.stringify(old.cards))throw Error('Changed old T05 SRS');if(JSON.stringify(s.navigation.pages['module/T05'].fields)!==JSON.stringify(old.navigation.pages['module/T05'].fields))throw Error('Lost T05 archive');const p=s.learning['T05-incidents'];if(p.attempts.length!==2||!p.attempts[0].reviews['T05-incidents-test-a-14']||!p.examDraft.answers['T05-incidents-test-a-14'])throw Error('Lost T05 history/review/next draft');if(p.answers['T05-incidents-writing-2']!==${JSON.stringify(full)}||p.answers['T05-incidents-writing-9']!==${JSON.stringify(revised)})throw Error('Lost distinct full drafts');if(s.drafts.T05!==old.drafts.T05)throw Error('Lost T05 old notes');}`);
 console.log('T05 smoke passed: nine banks, A/B tests, hidden listening, full original/revision/exam drafts, 0→16→127 published steps not full T05 or mastery, archive/SRS/reviews/history, nested routes, appendix and mobile.');
}
