import {modules,subtopics,courseStats,vocabulary,levels} from '/data/course.mjs';
import {referencePages,referenceSources} from '/data/reference.mjs';
import {unitById,unitState,unitWorkProgress,topicWorkProgress,isOpen,checkAnswer,scoreUnitTest,submitUnitTest,startUnitTest,buildPlan} from '/engine.mjs';

export function createLearningUI({main,esc,heading,getState,save,notify,speak,download}) {
 const state=()=>getState();
 const bind=(id,event,fn)=>document.getElementById(id)?.addEventListener(event,fn);
 const topic=id=>modules.find(m=>m.id===id);
 const labels={practice:'Практика',reading:'Чтение',listening:'Аудирование',writing:'Письмо',speaking:'Речь',review:'Повторение'};
 const referenceOrder=['alphabet','sounds','numbers-time','time-arrangements','nouns-articles','determiners-possession','personal-pronouns','be-questions','present-simple','present-continuous','quantity','place','past-simple','past-narrative','future-choices','present-perfect','perfect-continuous','past-perfect','habits-adaptation','hypothetical-conditions','wishes-possibility','passive-forms','service-arrangements','reported-speech','questions-tags','text-cohesion','word-building','email-writing','past-duration','future-frame','future-result','counterfactuals','past-modal-choices','relative-precision','participle-clauses','group-determiners','register-hedging','argument-concession','lexical-precision','ellipsis-substitution','presentation-signposts','discussion-decisions','inversion-focus','cleft-focus','fronting-information','reporting-passive','mandative-choices','modal-distance','comparison','rules-conditions','relative-clauses','verb-patterns','phrasal-patterns','tenses','irregular'];
 const referenceRank=id=>{const rank=referenceOrder.indexOf(id);return rank<0?referenceOrder.length:rank;};
 const statusLabels={'awaiting-review':'Ожидает проверки открытых ответов','awaiting-delayed-check':'Первичная проверка пройдена · нужен перенос через 7 дней',practicing:'Нужна дополнительная практика',incomplete:'Попытка не завершена'};
 const unitLink=(u,section='explain')=>`#unit/${u.id}/${section}`;
 function counts(u){const p=unitWorkProgress(state(),u.id);return {answered:p.practiceAnswered,total:p.practiceTotal,attempts:p.attempts};}
 function progressCopy(p){return p.kind==='expanded'?{
  label:'Общий прогресс работы',
  counts:`Практика: ${p.practiceAnswered}\u00a0/\u00a0${p.practiceTotal} ответов · Тесты отправлены: ${p.testsSubmitted}\u00a0/\u00a0${p.testsTotal}`,
  note:p.percent===100?'Первый проход заполнен. Проверка качества, работа над ошибками и отложенное применение ещё обязательны.':'Заполнение и отправка, не оценка знаний. Качество — в разборе тестов.'
 }:{label:'Самопроверка краткой версии',counts:p.completed?'Отметка самопроверки установлена':'Самопроверка ещё не отмечена',note:'Подробный учёт появится после расширения. Эта отметка не подтверждает освоение.'};}
 function progressHtml(id,compact=false){
  const p=topicWorkProgress(state(),id),copy=progressCopy(p),prefix=`topic-progress-${id}`;
  return `<section class="topic-progress ${compact?'compact':''}" data-topic-progress="${id}" data-progress-kind="${p.kind}"><div class="progress-heading"><span id="${prefix}-label">${id} · ${copy.label}</span><strong class="progress-percent">${p.percent}%</strong></div><progress max="${p.total}" value="${p.completed}" aria-labelledby="${prefix}-label" aria-describedby="${prefix}-counts ${prefix}-note"></progress><p class="progress-counts" id="${prefix}-counts">${copy.counts}</p><p class="progress-note" id="${prefix}-note">${copy.note}</p>${!compact&&p.kind==='expanded'?'<details><summary>Как считается шкала</summary><p>Один непустой ответ практики — один шаг. Один полностью отправленный итоговый тест каждой подтемы — ещё один шаг. Процент = выполненные шаги / все эти шаги топика; округление вниз. Подтемы разного размера не усредняются. Повторные варианты не добавляют проценты, черновик теста пока не засчитывается.</p><p>100% означает, что заполнена практика и отправлен хотя бы один тест каждой подтемы, а не что все ответы верны. Чтение страницы, карточки, время и заметки не увеличивают эту шкалу. Для освоения нужны разбор ошибок, оценка письма и реальной речи, затем применение через 7 дней.</p></details>':''}</section>`;
 }
 function refreshProgress(){
  main.querySelectorAll('[data-topic-progress]').forEach(node=>{
   const p=topicWorkProgress(state(),node.dataset.topicProgress),copy=progressCopy(p);
   const bar=node.querySelector('progress');bar.max=p.total;bar.value=p.completed;
   node.querySelector('.progress-percent').textContent=`${p.percent}%`;
   node.querySelector('.progress-counts').textContent=copy.counts;
   node.querySelector('.progress-note').textContent=copy.note;
  });
  const counter=document.getElementById('unit-work-counts');
  if(counter){const c=counts(unitById(counter.dataset.unit));counter.textContent=`${c.answered} из ${c.total} ответов практики заполнено · попыток итогового теста: ${c.attempts} · автосохранение`;}
 }
 function home(){
  const bookmark=state().bookmark;
  main.innerHTML=heading('ЛИЧНОЕ УЧЕБНОЕ ПРОСТРАНСТВО','Английский. С пониманием.','Разобраться в устройстве языка, много практиковаться и возвращаться к трудному — в своём темпе.')+
   `<section class="hero"><div><p class="eyebrow">УЧИТЬСЯ ПОСЛЕДОВАТЕЛЬНО</p><h2>${bookmark?'Продолжить с места остановки':'От первых звуков к свободному выражению мысли'}</h2><p>Топики и подтемы не привязаны к минутам. Можно остановиться в середине задания: ответы и черновики сохраняются.</p><div class="actions"><a class="button" id="continue-learning" href="${bookmark?'#'+esc(bookmark.route):'#module/P01'}">${bookmark?'Продолжить работу':'Открыть первый топик'} →</a><a class="button secondary" href="#assessment">Определить уровень</a></div></div><div class="hero-mark" aria-hidden="true">Aa<span>learn · use · revisit</span></div></section>
   <div class="grid stats"><div class="card"><span class="stat">${courseStats.topics}</span><span>топиков в карте курса</span></div><div class="card"><span class="stat">${courseStats.subtopics}</span><span>расширенных подтем с тестами</span></div><div class="card"><span class="stat">${vocabulary.length}</span><span>слов и выражений с IPA</span></div></div>
   <div class="section-heading"><h2>Три опоры обучения</h2><a href="#course">Карта курса →</a></div><div class="grid"><a class="feature-card" href="#module/P01"><span class="step-number">01</span><h3>Понять механизм</h3><p>Объяснения, контрасты, разбор примеров и справочные приложения.</p></a><a class="feature-card" href="#cards"><span class="step-number">02</span><h3>Применять и вспоминать</h3><p>Разнородная практика, свои тексты, диалоги и карточки выражений.</p></a><a class="feature-card" href="#plan"><span class="step-number">03</span><h3>Проверить результат</h3><p>Тест после подтемы, разбор пробелов и отложенное применение.</p></a></div>
   <div class="notice"><strong>Переработка содержания идёт.</strong> Расширен ${courseStats.expanded} из ${courseStats.topics} топиков: ${courseStats.practice} тренировочных заданий и ${courseStats.testTasks} заданий итоговых тестов. Остальные материалы пока являются краткой первой версией — не полным наполнением уровней.</div><p class="muted">Личный ориентир: ${state().profile.minutes} мин, ${state().profile.days} дней в неделю. Он не меняет объём курса и ничего не завершает автоматически.</p>`;
 }
 let selected='all',search='';
 function course(){
  const fields=state().navigation.pages.course?.fields??{};selected=fields.level??'all';search=fields.search??'';
  main.innerHTML=heading('УРОВЕНЬ → ТОПИК → ПОДТЕМЫ','Карта курса','Выбирайте материал по целям и предпосылкам. Размер топика определяется содержанием, не длительностью занятия.')+
   `<details><summary>Что показывает прогресс?</summary><p>Шкала каждого топика учитывает ответы практики и по одному отправленному тесту каждой подтемы. Это не процент освоения языка. Правила подсчёта — внутри топика; для кратких версий доступна только отметка самопроверки.</p></details><div class="filter-bar"><label>Уровень<select id="level"><option value="all">Все уровни</option>${levels.map(l=>`<option ${selected===l?'selected':''}>${l}</option>`).join('')}<option value="technical" ${selected==='technical'?'selected':''}>Техническая ветка</option></select></label><label>Поиск<input id="search" value="${esc(search)}" placeholder="Тема, конструкция, навык"></label><a href="#references">Справочные приложения →</a></div><div id="module-list" class="module-list"></div>`;
  const list=()=>{document.getElementById('module-list').innerHTML=modules.filter(m=>(selected==='all'||m.level===selected||(selected==='technical'&&m.track==='technical'))&&`${m.id} ${m.title} ${m.focus} ${m.subtopics.map(u=>u.title).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(m=>`<article class="module-row"><div><span class="pill">${m.level}</span><span class="content-badge ${m.subtopics.length?'expanded':''}">${m.subtopics.length?`${m.subtopics.length} наполненные подтемы`:'Краткая версия · расширение впереди'}</span><h3><a href="#module/${m.id}">${m.id} · ${esc(m.title)}</a></h3><small>${esc(m.focus)}</small>${progressHtml(m.id,true)}</div><a class="arrow-link" href="#module/${m.id}" aria-label="Открыть ${esc(m.title)}">→</a></article>`).join('')||'<p>Совпадений нет. Попробуйте другой запрос.</p>';};
  bind('level','change',e=>{selected=e.target.value;list();});bind('search','input',e=>{search=e.target.value;list();});list();
 }
 function topicView(id){
  const m=topic(id);if(!m)return false;if(!m.subtopics.length)return false;
  main.innerHTML=`<div class="breadcrumbs"><a href="#course">Карта курса</a><span>/ ${m.level} / ${m.id}</span></div>`+heading('ТОПИК',m.title,'Подтемы идут по смыслу. Продолжайте столько, сколько нужно для уверенного применения; к любому разделу можно вернуться.')+progressHtml(id)+
   `<p>Предпосылки: ${m.prerequisites.map(p=>`<a href="#module/${p}">${p}</a>`).join(', ')||'начало курса'}. <a href="#references">Все приложения →</a></p>${state().moduleProgress[id]?.selfChecked?'<p class="notice">Сохранена ваша самопроверка прежней краткой версии. Она не засчитывает новые подтемы и тесты.</p>':''}<div class="unit-list">${m.subtopics.map((u,i)=>{const c=counts(u);return `<article class="unit-card"><span class="step-number">${String(i+1).padStart(2,'0')}</span><div><h2><a href="${unitLink(u)}">${esc(u.title)}</a></h2><p>${u.goals.map(g=>esc(g.label)).join(' · ')}</p><div class="unit-meta"><span>${c.answered} / ${c.total} ответов практики</span><span>${u.tests.length} варианта теста</span><span>${c.attempts?'Попыток: '+c.attempts:'Итоговый тест ещё не отправлен'}</span></div><progress max="${c.total}" value="${c.answered}" aria-label="Заполненные ответы практики"></progress><a href="${unitLink(u)}">Открыть подтему →</a></div></article>`;}).join('')}</div><div class="notice">Заполненный ответ, самопроверка и освоение — разные состояния. Открытые задания проверяет агент или преподаватель; после первичной проверки нужен перенос на новый материал через 7 дней.</div><h2>Общий черновик топика</h2><label for="draft">Сохранённые заметки (в том числе из первой версии)</label><textarea id="draft" maxlength="20000">${esc(state().drafts[id]??'')}</textarea>`;
  // Old drill IDs remain in navigation after a topic gains subtopics. Render
  // their original prompts and answers so page capture cannot silently drop them.
  const archived=Object.entries(state().navigation.pages['module/'+id]?.fields??{}).filter(([key])=>/^drill\d+$/.test(key)&&Number(key.slice(5))<m.drills.length);
  if(archived.length)main.innerHTML+=`<details id="legacy-practice"><summary>Ответы прежней краткой версии</summary><p>Архив сохранён без переноса оценок в новые подтемы. Ответы можно выделить и скопировать; новые задания выполняются отдельно.</p>${archived.map(([key,answer])=>`<label for="${esc(key)}">${esc(m.drills[Number(key.slice(5))][0])}</label><textarea id="${esc(key)}" readonly maxlength="20000">${esc(answer)}</textarea>`).join('')}</details>`;
  bind('draft','input',e=>{state().drafts[id]=e.target.value;save();});return true;
 }
 function taskHtml(task,answer,index,feedback=''){
  const multiline=task.kind!=='short';
  return `<article class="task" id="task-${task.id}"><div class="task-top"><span class="task-number">${index+1}</span><span class="muted">${{short:'Краткий ответ',sentence:'Предложение',text:'Развёрнутый ответ',speech:'Устная работа · проверка слушателем'}[task.kind]}</span></div><label for="answer-${task.id}">${esc(task.prompt)}</label>${multiline?`<textarea id="answer-${task.id}" data-task="${task.id}" maxlength="20000" placeholder="${task.kind==='speech'?'Заметки, транскрипт, путь к отдельной записи для преподавателя. Это не заменяет само аудио.':'Введите свой ответ. Другие верные формулировки допустимы.'}">${esc(answer??'')}</textarea>`:`<input id="answer-${task.id}" data-task="${task.id}" value="${esc(answer??'')}" maxlength="20000" autocomplete="off">`}<div class="feedback" id="feedback-${task.id}" aria-live="polite">${feedback}</div></article>`;
 }
 function feedback(task,answer){
  if(!answer?.trim())return 'Ответ ещё не введён.';
  if(isOpen(task))return `<strong>Нужна содержательная проверка.</strong> Критерии: ${esc(task.explanation)}<details><summary>Один из возможных образцов — не единственный правильный ответ</summary>${esc(task.answer)}</details>`;
  return `<strong>${checkAnswer(answer,task.answer)?'Верно.':'Нужно разобрать.'}</strong> ${esc(task.explanation)}${checkAnswer(answer,task.answer)?'':`<p>Ключ: ${esc(task.answer.replaceAll('|',' / '))}. Если ваш ответ также допустим, обсудите его с преподавателем: строковая проверка ограничена.</p>`}`;
 }
 function unitView(id,section='explain'){
  const u=unitById(id);if(!u){main.innerHTML='<h1>Подтема не найдена</h1><a href="#course">К карте курса</a>';return;}
  const m=topic(u.topic),p=unitState(state(),id),c=counts(u);
  const sections=[['explain','Механизм'],['examples','Примеры'],...u.banks.map(b=>[b.id,b.navLabel??(b.kind==='writing'&&b.tasks.some(t=>t.kind==='speech')?'Письмо и речь':b.kind==='practice'&&b.id!=='practice'?b.title:labels[b.kind]??b.title)]),['test','Итоговый тест']];
  if(!sections.some(([s])=>s===section))section='explain';
  main.innerHTML=`<div class="breadcrumbs"><a href="#course">Курс</a><span>/ ${m.level} /</span><a href="#module/${m.id}">${m.id}</a><span>/ Подтема ${m.subtopics.indexOf(u)+1}</span></div>`+heading(u.id,u.title)+
   `${progressHtml(m.id,true)}<p class="muted" id="unit-work-counts" data-unit="${id}">${c.answered} из ${c.total} ответов практики заполнено · попыток итогового теста: ${p.attempts.length} · автосохранение</p><nav class="section-tabs" aria-label="Разделы подтемы">${sections.map(([s,label])=>`<a href="${unitLink(u,s)}" ${section===s?'aria-current="page"':''}>${esc(label)}</a>`).join('')}</nav><div id="unit-content"></div><div class="unit-bottom"><a href="#module/${u.topic}">← Подтемы топика</a><span>Остановиться можно в любой момент. Ответы сохраняются.</span></div>`;
  const content=document.getElementById('unit-content');
  if(section==='explain')content.innerHTML=`<section class="goals"><h2>Что проверим после подтемы</h2><ul>${u.goals.map(g=>`<li>${esc(g.label)}</li>`).join('')}</ul><p>Предпосылки: ${u.prerequisites.map(id=>`<a href="#unit/${id}/explain">${esc(unitById(id).title)}</a>`).join(', ')||'нет'}.</p></section>${u.explanation.map(e=>`<section class="explanation"><h2>${esc(e.title)}</h2><p>${esc(e.text)}</p></section>`).join('')}<div class="actions">${u.references.map(id=>`<a class="button secondary" href="#references/${id}">${esc(referencePages.find(r=>r.id===id).title)}</a>`).join('')}</div>${u.sources?.length?`<h2>Источники для сверки</h2><ul>${u.sources.map(([title,url])=>`<li><a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(title)}</a></li>`).join('')}</ul>`:''}<a class="button" href="${unitLink(u,'examples')}">Разобрать примеры →</a>`;
  else if(section==='examples')content.innerHTML=`<h2>От формы к смыслу</h2>${u.examples.map((e,i)=>`<article class="example"><span class="muted">${String(i+1).padStart(2,'0')}</span><p lang="en" class="example-en">${esc(e.en)}</p><p>${esc(e.ru)}</p><small>${esc(e.why)}</small></article>`).join('')}<a class="button" href="${unitLink(u,u.banks[0].id)}">Перейти к практике →</a>`;
  else if(section==='test')renderTest(u,p,content);
  else {
   const b=u.banks.find(b=>b.id===section);
   content.innerHTML=`<h2>${esc(b.title)}</h2>${b.diagram?`<figure class="lesson-diagram"><div class="diagram-frame" tabindex="0" role="region" aria-label="Схема: горизонтальная прокрутка"><img src="${esc(b.diagram.src)}" alt="${esc(b.diagram.alt)}" width="720" height="560"></div><figcaption>${esc(b.diagram.caption)} <a href="${esc(b.diagram.src)}" target="_blank" rel="noreferrer">Открыть схему отдельно</a></figcaption></figure>`:''}${b.kind==='listening'?`<p>Сначала прослушайте, затем ответьте. Транскрипт доступен после проверки серии. Синтетический голос — учебная поддержка, не всё разнообразие живой речи.</p><button id="listen-bank">Прослушать материал</button>`:b.passage?`<div class="reading" lang="en">${esc(b.passage).replaceAll('\n','<br>')}</div>`:''}${b.tasks.map((t,i)=>taskHtml(t,p.answers[t.id],i,p.checks[t.id]?.answer===p.answers[t.id]?feedback(t,p.answers[t.id]):'')).join('')}<div class="actions"><button id="check-bank">Проверить заполненные ответы</button><a class="button secondary" href="${unitLink(u,'test')}">К итоговому тесту</a>${b.tasks.some(t=>t.kind==='speech')?'<a href="#speech">Речевая практика →</a>':''}</div><div id="bank-transcript"></div>`;
   const transcript=()=>{if(b.kind==='listening'&&b.tasks.every(t=>p.checks[t.id]?.answer?.trim()))document.getElementById('bank-transcript').innerHTML=`<details><summary>Транскрипт после попытки</summary><p lang="en">${esc(b.passage)}</p></details>`;};transcript();
   bind('listen-bank','click',()=>speak(b.passage));
   content.querySelectorAll('[data-task]').forEach(input=>input.addEventListener('input',()=>{p.answers[input.dataset.task]=input.value;document.getElementById('feedback-'+input.dataset.task).textContent='';save();refreshProgress();}));
   bind('check-bank','click',()=>{for(const t of b.tasks){if(p.answers[t.id]?.trim())p.checks[t.id]={answer:p.answers[t.id],date:new Date().toISOString()};document.getElementById('feedback-'+t.id).innerHTML=feedback(t,p.answers[t.id]);}save();transcript();notify('Самопроверка сохранена. Открытые ответы требуют разбора по критериям.');});
  }
 }
 function renderTest(u,p,content){
  const draft=p.examDraft,test=draft&&u.tests.find(t=>t.id===draft.variant);
  content.innerHTML=`<h2>Контроль после подтемы</h2><p>Новые задания проверяют цели подтемы. Можно остановиться и вернуться: черновик сохраняется. Ключи появятся после отправки всей попытки. Если не знаете, напишите «Не знаю». Открытые ответы и речь не оцениваются по совпадению с образцом.</p>${test?`<h3>${esc(test.title)}</h3>${p.attempts.some(a=>a.variant===test.id)?'<p class="warning">Этот вариант уже встречался. Повтор полезен для закрепления, но не доказывает перенос на незнакомый материал. Для следующей независимой проверки нужен новый вариант от преподавателя.</p>':''}<form id="unit-test">${test.tasks.map((t,i)=>taskHtml(t,draft.answers[t.id],i)).join('')}<button type="submit">Отправить попытку и открыть разбор</button></form>`:'<button id="new-unit-test">Начать следующий вариант</button>'}<section id="test-history"><h2>История и разбор</h2>${p.attempts.length?'':'<p>Отправленных попыток пока нет. Тренировочные ответы хранятся отдельно.</p>'}${[...p.attempts].reverse().map((a,i)=>attemptHtml(u,a,i===0)).join('')}</section>`;
  content.querySelectorAll('[data-task]').forEach(input=>input.addEventListener('input',()=>{p.examDraft.answers[input.dataset.task]=input.value;save();}));
  bind('unit-test','submit',e=>{e.preventDefault();try{submitUnitTest(state(),u.id);save();renderTest(u,p,content);refreshProgress();document.getElementById('test-history').scrollIntoView({block:'start'});notify('Попытка сохранена. Закрытая часть проверена; открытые ответы ожидают оценки.');}catch(error){notify(error.message);}});
  bind('new-unit-test','click',()=>{startUnitTest(state(),u.id);save();renderTest(u,p,content);});
  content.querySelectorAll('[data-review]').forEach(form=>form.addEventListener('submit',e=>{
   e.preventDefault();const data=new FormData(form),attempt=p.attempts.find(a=>a.id===form.dataset.attempt),tid=form.dataset.review;
   const review={score:Number(data.get('score')),reviewer:String(data.get('reviewer')).trim(),evidence:String(data.get('evidence')).trim(),date:new Date().toISOString(),heardAudio:data.get('heardAudio')==='on'};
   const task=u.tests.find(t=>t.id===attempt.variant).tasks.find(t=>t.id===tid);
   if(!review.reviewer||review.evidence.length<10||(task.kind==='speech'&&!review.heardAudio)){notify('Нужны проверяющий, содержательное основание и прослушанное аудио для речи.');return;}
   attempt.reviews[tid]=review;save();renderTest(u,p,content);notify('Внешняя оценка записана. Это не автоматическая сертификация навыка.');
  }));
 }
 function attemptHtml(u,a,open){
  const result=scoreUnitTest(u,a),test=u.tests.find(t=>t.id===a.variant);
  return `<details class="attempt" ${open?'open':''}><summary>${esc(test.title)} · ${esc(new Date(a.date).toLocaleString('ru'))} · ${result.correct}/${result.total} закрытых</summary><p class="notice">${statusLabels[result.status]}. Без отложенного применения подтема не считается подтверждённо освоенной.</p><div class="goal-results">${result.goals.map(g=>`<div><strong>${esc(g.label)}</strong><p>Успешно: ${g.passed}/${g.total} · ожидает проверки: ${g.pending} · пробелы: ${g.retry}</p>${g.retry?`<a href="${unitLink(u,g.bank)}">Вернуться к адресной практике →</a>`:''}</div>`).join('')}</div>${test.tasks.map(t=>{const r=result.rows.find(x=>x.id===t.id),review=a.reviews[t.id];return `<div class="answer-review"><h3>${esc(t.prompt)}</h3><p class="submitted-answer">Ваш ответ: ${esc(a.answers[t.id])}</p><p>${{passed:'Первичная проверка: успешно',retry:'Нужно повторение',pending:'Ожидает содержательной проверки',missing:'Нет ответа'}[r.status]}</p><details><summary>${isOpen(t)?'Критерии и возможный образец':'Ключ и объяснение'}</summary><p>${esc(t.answer.replaceAll('|',' / '))}</p><p>${esc(t.explanation)}</p></details>${review?`<p>Проверяющий: ${esc(review.reviewer)} · ${review.score}/4 · ${esc(review.date)}</p><p>${esc(review.evidence)}</p>`:isOpen(t)?`<details><summary>Записать оценку после обсуждения с агентом / преподавателем</summary><p>Не выставляйте оценку по одному образцу. 0 — навык не показан; 1 — большие пробелы; 2 — частично; 3 — задача выполнена с небольшими ошибками; 4 — уверенно и самостоятельно.</p><form data-review="${t.id}" data-attempt="${a.id}"><label>Кто проверил<input name="reviewer" required maxlength="200"></label><label>Оценка<select name="score">${[0,1,2,3,4].map(n=>`<option>${n}</option>`).join('')}</select></label><label>Цитата ответа, основание, ошибки и следующий шаг<textarea name="evidence" required minlength="10" maxlength="5000"></textarea></label>${t.kind==='speech'?'<label><input type="checkbox" name="heardAudio" required>Проверяющий слышал реальное аудио / живую речь, не только транскрипт</label>':''}<button>Сохранить внешнюю оценку</button></form></details>`:''}</div>`;}).join('')}</details>`;
 }
 function references(id){
  const page=referencePages.find(r=>r.id===id);
  if(!page){main.innerHTML=heading('СПРАВОЧНИК','Приложения к курсу','Полные таблицы для указанной области охвата. Пользуйтесь ими во время практики, а не заучивайте всё за один подход.')+`<div class="grid">${[...referencePages].sort((a,b)=>referenceRank(a.id)-referenceRank(b.id)).map(r=>`<a class="feature-card" href="#references/${r.id}"><span class="pill">${r.rows.length} позиций${r.families?' + '+r.families.length+' производных':''}</span><h2>${esc(r.title)}</h2><p>${r.practice.length} задач для самопроверки →</p></a>`).join('')}</div>`;return;}
  main.innerHTML=`<a href="#references">← Все приложения</a>`+heading('СПРАВОЧНОЕ ПРИЛОЖЕНИЕ',page.title)+page.intro.map(x=>`<p>${esc(x)}</p>`).join('')+`<label for="reference-search">Поиск внутри таблицы<input id="reference-search" placeholder="Слово, символ или форма"></label><div class="table-wrap" tabindex="0" role="region" aria-label="Таблица ${esc(page.title)}"><table class="reference-table"><thead><tr>${page.headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody id="reference-rows"></tbody></table></div>${page.families?`<h2>Производные семейства</h2><div class="table-wrap" tabindex="0" role="region" aria-label="Производные глаголы"><table><thead><tr><th>V1</th><th>V2</th><th>V3</th><th>Значение</th></tr></thead><tbody>${page.families.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}<h2>Применение и самопроверка</h2><ol>${page.practice.map(([q,a])=>`<li>${esc(q)}<details><summary>Разбор после самостоятельной попытки</summary>${esc(a)}</details></li>`).join('')}</ol><h2>Источники для сверки</h2><p>Таблицы, объяснения и упражнения здесь авторские. Для записей дикторов, вариантов и дополнительных описаний:</p><ul>${(page.sources??referenceSources).map(([title,url])=>`<li><a href="${url}" target="_blank" rel="noreferrer">${esc(title)}</a></li>`).join('')}</ul>`;
  const rows=query=>{document.getElementById('reference-rows').innerHTML=page.rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${page.headers.length}">Совпадений нет.</td></tr>`;};rows(state().navigation.pages['references/'+id]?.fields['reference-search']??'');bind('reference-search','input',e=>rows(e.target.value));
 }
 function planView(){
  const plan=buildPlan(state());main.innerHTML=heading('СОДЕРЖАНИЕ, А НЕ ТАЙМЕР','Ваш маршрут','Очередь определяется диагностикой и предпосылками. Нет пяти обязательных занятий на топик или нормы страниц за неделю.');
  if(!plan){main.innerHTML+='<div class="card"><p>Стартовый уровень неизвестен. Пройдите диагностику, затем обсудите письмо и речь с преподавателем. Весь опубликованный материал доступен и без теста.</p><a class="button" href="#assessment">К диагностике</a></div>';return;}
  main.innerHTML+=`<p class="warning">Предварительный учебный старт: ${plan.start}. Это не подтверждённый CEFR. Нужна оценка: ${plan.pending.join(', ')||'ручные оценки внесены — проверьте основания'}.</p><p>Личный ориентир: ${plan.minutes} минут, ${plan.days} дней в неделю. Изменение времени не меняет эту очередь и объём заданий. Через две недели обсудите фактические результаты; через четыре — дальнейший маршрут, без обещания закончить определённое число тем.</p><button id="export-plan">Скачать план.md</button><h2>Очередь и основания выбора</h2>${plan.items.map(m=>`<article class="module-row"><div><span class="pill">${m.level}</span><h3><a href="#module/${m.id}">${m.id} · ${esc(m.title)}</a></h3><p>${esc(m.reason)}</p><small>${m.subtopics.length?`${m.subtopics.length} подтем · пройти отдельный тест после каждой`:'Материал пока краткий; расширение ещё не завершено'}${m.checks.length?'; сначала проверить предпосылки: '+m.checks.join(', '):''}</small>${progressHtml(m.id,true)}</div></article>`).join('')}`;
  bind('export-plan','click',()=>download('plan.md',`# Предварительный маршрут\n\nЦель: ${state().profile.goal}\nЛичный ориентир: ${plan.minutes} мин, ${plan.days} дней в неделю; он не меняет объём работы.\nСтарт: ${plan.start}, не подтверждённый CEFR.\nНужна оценка: ${plan.pending.join(', ')}.\n\n${plan.items.map(m=>`- ${m.id} ${m.title}: ${m.reason}. Проверить: ${m.checks.join(', ')||'нет дополнительных предпосылок'}.`).join('\n')}\n\nПосле каждой подтемы: отдельный тест, разбор пробелов, проверка открытых ответов. Через 7 дней — отложенное применение. На ближайшие четыре недели не назначается фиксированное число тем; продолжайте по фактическому прогрессу. Пересмотр через две недели и после контрольного проекта.\n`,'text/markdown;charset=utf-8'));
 }
 return {home,course,topic:topicView,unit:unitView,references,plan:planView,progressHtml,refreshProgress};
}
